version: '3'

services:
  pdf_service:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile-compose
    container_name: koa_server
    environment:
      - OUTPUT_DIR=result
    volumes:
      - ./result:/app/result
    ports:
      - 3000:3000
    logging: 
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"